require 'rails_admin'
require 'rails_admin_thumbnail_limited_multiselect_field/rails_admin/config/fields/types/thumbnail_limited_multiselect'
load 'rails_admin_thumbnail_limited_multiselect_field/engine.rb'